/*
 * Copyright (C) 2015 cepardov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package vista;


import beans.UsuarioBeans;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import sistema.Service;
import utilidades.DateTime;

/**
 *
 * @author cepardov
 */
public class Menu extends javax.swing.JFrame {
    UsuarioBeans usuariobeans=new UsuarioBeans();
    Usuarios usuario=new Usuarios();
    Fabricante fabricante=new Fabricante();
    Proveedor proveedor=new Proveedor();
    Ejecutivo ejecutivo = new Ejecutivo();
    DateTime dt=new DateTime();
    Timer timer;
    
    String loginId = null;
    String loginNombre = null;
    String loginApellido = null;
    String loginUsuario = null;
    String loginClave = null;//Encriptado
    String loginPrivilegio = null;
    
    public Menu() {}
    public Menu(String idUsuario, String nombre, String apellido, String usuario,String clave, String privilegio, String enabled) {
        initComponents();
        loginId = idUsuario;
        loginNombre = nombre;
        loginApellido = apellido;
        loginUsuario = usuario;
        loginClave = clave;
        loginPrivilegio = privilegio;
        this.busy(1);
        timer = new Timer();        
        timer.schedule(new RemindTask(), 0, 15000);
        this.btnUsuario.setText(nombre+" "+apellido);
        this.busy(0);
    }
    /**
     * Muestra cursor de carga mientras reliza una operación
     * @param estado 0=Normal, 1=cargando
     */
    private void busy(int estado){
        switch (estado) {
            case 1:
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                break;
            case 0:
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                break;
            default:
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
                break;
        }
    }
    
    private void reloj(){
//        this.lblHora.setText(dt.gethoraHM());
    }
    
    private void barraEstado(){
        usuario.lblErrorBusqueda.setText("");
//        this.lblEstado.setText("Barra Estado");
    }
    
    private void reset(){
        fabricante.lblErrorBusqueda.setText("");
        proveedor.lblErrorBusqueda.setText("");
        ejecutivo.lblErrorBusqueda.setText("");
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("iconos/menu.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnUsuario = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenuItem();
        btnCerrarSesion = new javax.swing.JMenuItem();
        btnCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnCategorias = new javax.swing.JMenuItem();
        btnFabricantes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnProductos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());

        btnUsuario.setText("Usuario");

        jMenu1.setText("Administrador");

        btnUsuarios.setText("Gestor de Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(btnUsuarios);

        btnUsuario.add(jMenu1);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        btnUsuario.add(btnCerrarSesion);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        btnUsuario.add(btnCerrar);

        jMenuBar1.add(btnUsuario);

        jMenu2.setText("Catálogo");

        jMenuItem1.setText("Proveedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        btnCategorias.setText("Categorías");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(btnCategorias);

        btnFabricantes.setText("Fabricantes");
        btnFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabricantesActionPerformed(evt);
            }
        });
        jMenu2.add(btnFabricantes);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Modulos");

        btnProductos.setText("Gestor de Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jMenu4.add(btnProductos);

        jMenuItem4.setText("Gestor de Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Contactos");

        jMenuItem2.setText("Ejecutivos Proveedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        new Service().cerrarApp();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        p.add(usuario);
        usuario.setTitle("Gestor de Usuarios");
        usuario.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabricantesActionPerformed
        // TODO add your handling code here:
        
        p.add(fabricante);
        fabricante.limpiar();
        fabricante.setTitle("Gestor de Fabricantes");
        fabricante.setVisible(true);
    }//GEN-LAST:event_btnFabricantesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        p.add(proveedor);
        proveedor.setTitle("Gestor Proveedores");
        proveedor.limpiar();
        proveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        p.add(ejecutivo);
        ejecutivo.setTitle("Gestor Ejecutivos");
        ejecutivo.limpiar();
        ejecutivo.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
        Categorias categorias=new Categorias();
        p.add(categorias);
        categorias.setTitle("Gestor de Categorías");
//        categorias.limpiar();
        categorias.setVisible(true);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        Producto producto=new Producto();
        p.add(producto);
        producto.setSize(p.getSize());
        producto.setTitle("Gestión de Productos");
        producto.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:       
        Venta venta = new Venta(loginId,loginNombre,loginApellido,loginUsuario,loginClave,loginPrivilegio);
        p.add(venta);
        venta.setSize(p.getSize());
//        informepericial5.setSize(d.getSize());
        venta.setTitle("Gestor de Ventas");
        venta.setInstanciaVenta(true);
        venta.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    class RemindTask extends TimerTask {

        @Override
        public void run() {
            reloj();
            barraEstado();
            reset();
            //
//            cargaTablaInforme();
//            try {
////                BuscaCita();
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCategorias;
    private javax.swing.JMenuItem btnCerrar;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnFabricantes;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenu btnUsuario;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JDesktopPane p;
    // End of variables declaration//GEN-END:variables
}
